version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: yes
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_apache.sh
    - location: scripts/cleanup.sh
      runas: root
  ApplicationStart:
    - location: scripts/changepermission.sh
      timeout: 30
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/status_apache.sh
      timeout: 30
      runas: root
